### ISSUE TITLE
Redux

### ISSUE THREAD

**Issue by nh83012001** [learn-co-curriculum/react-introduction-to-react-router#5]
The first paragraph talks about how we have learned to move state to a store using Redux and that's a couple weeks after this gets deployed.

**Comment by DanielSeehausen** [comment]
Thank you for spotting this issue and providing feedback @nh83012001. 

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
