### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by dkStephanos** [learn-co-curriculum/react-introduction-to-react-router#6]
"We have to plan out all the possibilities that might happen on the Client-Side, this might feel like we are repeating designs that we have already completed with **out** server routes and and models."

out => our

**Comment by DanielSeehausen** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
