### ISSUE TITLE
Suggestions for including information in this lesson re: accessibility issues around SPAs for visually impaired folks using text readers. 

### ISSUE THREAD

**Issue by emikojima** [learn-co-curriculum/react-introduction-to-react-router#7]
Hello. I have read a few blog posts about how one of the drawbacks of SPAs is that it is difficult for text readers/assistive technologies to read the app. It would be great to include a few lines about this so people are aware! 

Here's a great [blog post ](https://blog.usejournal.com/getting-started-with-web-accessibility-in-react-9e591fdb0d52)about it. 

Thanks!

**Comment by sgharms** [comment]
Merged!
